import {
  ArrowRight,
  BarChart3,
  Bell,
  BellRing,
  Braces,
  Calendar,
  CheckCircle2,
  ChevronRight,
  Circle,
  Clock,
  Cloud,
  Database,
  DollarSign,
  Download,
  Eye,
  FileDown,
  FileText,
  Hash,
  Home,
  Landmark,
  Layers,
  LayoutDashboard,
  Lock,
  LogOut,
  Monitor,
  MoreHorizontal,
  Network,
  Package,
  Play,
  RefreshCw,
  Search,
  Server,
  ServerOff,
  Settings,
  ShieldCheck,
  Sheet,
  SlidersHorizontal,
  Store,
  Table,
  Target,
  Terminal,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Upload,
  Users,
  WifiOff,
} from 'lucide-react'

const iconMap = {
  alerts: Bell,
  arrowRight: ArrowRight,
  bell: Bell,
  calendar: Calendar,
  chart: TrendingUp,
  checkCircle: CheckCircle2,
  chevronRight: ChevronRight,
  circle: Circle,
  clock: Clock,
  dashboard: LayoutDashboard,
  database: Database,
  document: FileText,
  download: Download,
  eye: Eye,
  export: Upload,
  external: Cloud,
  file: FileText,
  fileCsv: Table,
  fileJson: Braces,
  filePdf: FileDown,
  fileXls: Sheet,
  filter: SlidersHorizontal,
  finance: Landmark,
  gateway: Server,
  gatewayOff: ServerOff,
  hash: Hash,
  home: Home,
  inventory: Package,
  kpis: BarChart3,
  layers: Layers,
  lock: Lock,
  logout: LogOut,
  monitor: Monitor,
  more: MoreHorizontal,
  network: Network,
  notification: BellRing,
  play: Play,
  refresh: RefreshCw,
  reports: FileText,
  sales: DollarSign,
  search: Search,
  services: Layers,
  settings: Settings,
  shield: ShieldCheck,
  store: Store,
  target: Target,
  terminal: Terminal,
  trash: Trash2,
  trend: TrendingUp,
  warning: TriangleAlert,
  users: Users,
  wifiOff: WifiOff,
}

export default function AppIcon({
  name,
  size = 20,
  strokeWidth = 2,
  className = '',
}) {
  const IconComponent = iconMap[name] || FileText

  return (
    <IconComponent
      aria-hidden="true"
      className={`app-icon ${className}`.trim()}
      size={size}
      strokeWidth={strokeWidth}
    />
  )
}
